### ISSUE TITLE
dnsimple expiration dates not in the format golang expects of json-encoded times

### ISSUE THREAD

**Issue by aranhoide** [weppos/go-dnsimple#3]
When trying to load my domains by using the code in the README I get:

    parsing time ""2015-03-20"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "T"

Changing the definition of `dnsimple.Domain` to use go`string` instead of go`time.Time*` works around this (I don't claim this is a proper fix; just trying to pinpoint the issue.)

**Comment by weppos** [comment]
That's interesting, I will investigate. I recently converted dates from `String` to `Time` in 1b6ea6f90f4724495b81cbc9fc0bb3c256e991da, but I had a couple of issues related to that.

**Comment by weppos** [comment]
I bet the issue is with the `expires_on` field that is a `Date` and not a `Time`.
